# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .static_page import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumiverse_github_credentials.google as __google
    google = __google
else:
    google = _utilities.lazy_import('pulumiverse_github_credentials.google')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "github-credentials",
  "mod": "google",
  "fqn": "pulumiverse_github_credentials.google",
  "classes": {
   "github-credentials:google:WorkloadIdentityPoolForGithub": "WorkloadIdentityPoolForGithub"
  }
 },
 {
  "pkg": "github-credentials",
  "mod": "index",
  "fqn": "pulumiverse_github_credentials",
  "classes": {
   "github-credentials:index:StaticPage": "StaticPage"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "github-credentials",
  "token": "pulumi:providers:github-credentials",
  "fqn": "pulumiverse_github_credentials",
  "class": "Provider"
 }
]
"""
)
