# yaml-language-server: $schema=https://raw.githubusercontent.com/pulumi/pulumi/master/pkg/codegen/schema/pulumi.json
---
name: github-credentials
resources:
  github-credentials:index:WorkloadIdentityPoolForGithub:
    isComponent: true
    inputProperties:
      identityPoolName:
        type: string
        description: The name of the identity pool.
    requiredInputs: []
    properties:
      identityPool:
        "$ref": "/google-native/v0.29.0/schema.json#/resources/google-native:iam%2Fv1:WorkloadIdentityPool"
        description: The identity pool resource.
language:
  csharp:
    packageReferences:
      Pulumi: 3.*
      Pulumi.Aws: 4.*
  go:
    generateResourceContainerTypes: true
    importBasePath: github.com/pulumiverse/pulumi-github-credentials/sdk/go/github-credentials
  nodejs:
    packageName: "@pulumiverse/github-credentials"
    dependencies:
      "@pulumi/aws": "^4.0.0"
      "@pulumi/google-native": "0.29.0"
    devDependencies:
      typescript: "5.0.4"
  python:
    packageName: pulumiverse_github_credentials
    requires:
      pulumi: ">=3.0.0,<4.0.0"
      pulumi-aws: ">=4.0.0,<5.0.0"
