// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { WorkloadIdentityPoolForGithubArgs } from "./workloadIdentityPoolForGithub";
export type WorkloadIdentityPoolForGithub = import("./workloadIdentityPoolForGithub").WorkloadIdentityPoolForGithub;
export const WorkloadIdentityPoolForGithub: typeof import("./workloadIdentityPoolForGithub").WorkloadIdentityPoolForGithub = null as any;
utilities.lazyLoad(exports, ["WorkloadIdentityPoolForGithub"], () => require("./workloadIdentityPoolForGithub"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "github-credentials:google:WorkloadIdentityPoolForGithub":
                return new WorkloadIdentityPoolForGithub(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("github-credentials", "google", _module)
