// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

import * as pulumiGoogleNative from "@pulumi/google-native";

export class WorkloadIdentityPoolForGithub extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'github-credentials:google:WorkloadIdentityPoolForGithub';

    /**
     * Returns true if the given object is an instance of WorkloadIdentityPoolForGithub.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WorkloadIdentityPoolForGithub {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WorkloadIdentityPoolForGithub.__pulumiType;
    }

    /**
     * The identity pool resource.
     */
    public /*out*/ readonly identityPool!: pulumi.Output<pulumiGoogleNative.iam.v1.WorkloadIdentityPool | undefined>;

    /**
     * Create a WorkloadIdentityPoolForGithub resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: WorkloadIdentityPoolForGithubArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["identityPoolName"] = args ? args.identityPoolName : undefined;
            resourceInputs["identityPool"] = undefined /*out*/;
        } else {
            resourceInputs["identityPool"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(WorkloadIdentityPoolForGithub.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a WorkloadIdentityPoolForGithub resource.
 */
export interface WorkloadIdentityPoolForGithubArgs {
    /**
     * The name of the identity pool.
     */
    identityPoolName?: pulumi.Input<string>;
}
