// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GithubCredentials.Google
{
    [GithubCredentialsResourceType("github-credentials:google:WorkloadIdentityPoolForGithub")]
    public partial class WorkloadIdentityPoolForGithub : global::Pulumi.ComponentResource
    {
        /// <summary>
        /// The identity pool resource.
        /// </summary>
        [Output("identityPool")]
        public Output<Pulumi.GoogleNative.IAM.V1.WorkloadIdentityPool?> IdentityPool { get; private set; } = null!;


        /// <summary>
        /// Create a WorkloadIdentityPoolForGithub resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public WorkloadIdentityPoolForGithub(string name, WorkloadIdentityPoolForGithubArgs? args = null, ComponentResourceOptions? options = null)
            : base("github-credentials:google:WorkloadIdentityPoolForGithub", name, args ?? new WorkloadIdentityPoolForGithubArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class WorkloadIdentityPoolForGithubArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the identity pool.
        /// </summary>
        [Input("identityPoolName")]
        public Input<string>? IdentityPoolName { get; set; }

        public WorkloadIdentityPoolForGithubArgs()
        {
        }
        public static new WorkloadIdentityPoolForGithubArgs Empty => new WorkloadIdentityPoolForGithubArgs();
    }
}
